name: Django CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  heroku_git_deploy_job:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy django to heroku
          uses: fpmi-hci/proekt12a-bulakhrutkevich@main
          with: 
            heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_email_address: ${{ secrets.HEROKU_EMAIL }}
            use_docker: true
            git_branch: main
